#!/bin/bash
# Factory Reset - Quick Reference Card

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          Rapiba Factory Reset - Quick Reference            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 COMMAND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "sudo rapiba --factory-reset"
echo ""

echo "⚠️  WHAT GETS DELETED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ /var/lib/rapiba/       (Duplicate database)"
echo "✓ /var/log/rapiba/       (All logs)"
echo "✓ /backup/               (All backups)"
echo "✓ /etc/rapiba/config     (Resets to default)"
echo ""

echo "🛡️  SAFETY FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Requires root (sudo)"
echo "2. Requires explicit confirmation (type 'FACTORY RESET')"
echo "3. Requires final confirmation (type 'Ja')"
echo ""

echo "📝 PROCESS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Stops all services"
echo "2. Deletes duplicate database"
echo "3. Deletes all logs"
echo "4. Deletes all backups"
echo "5. Resets configuration to defaults"
echo "6. Restarts services"
echo ""

echo "✅ WHEN TO USE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Complete system reset"
echo "• Corrupted database"
echo "• Clean slate before resale"
echo "• Testing/experimentation cleanup"
echo ""

echo "❌ WHEN NOT TO USE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• If you want to keep backups (use selective deletion instead)"
echo "• If you only want to delete logs"
echo "• If you only want to reset the database"
echo ""

echo "🔄 WHAT STAYS INSTALLED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• /usr/local/bin/rapiba (Binaries)"
echo "• /usr/local/lib/rapiba/ (Python modules)"
echo "• /etc/systemd/system/rapiba* (Services)"
echo "• /etc/udev/rules.d/99-rapiba.rules (udev rules)"
echo ""

echo "⏭️  NEXT STEPS AFTER RESET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Edit config: sudo nano /etc/rapiba/rapiba.conf"
echo "2. Or use quicksetup: sudo rapiba --quick-setup"
echo "3. Check status: rapiba --status"
echo ""

echo "🚫 CANNOT BE UNDONE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "This operation is PERMANENT and CANNOT be reversed!"
echo "All data in /backup/, /var/lib/rapiba/, and /var/log/rapiba/"
echo "will be COMPLETELY DELETED!"
echo ""

echo "💾 ALTERNATIVES FOR SELECTIVE CLEANUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Only delete logs:"
echo "  sudo rm -rf /var/log/rapiba/*"
echo ""
echo "Only delete database:"
echo "  sudo rm /var/lib/rapiba/duplicate_db.sqlite3"
echo ""
echo "Only delete backups:"
echo "  sudo rm -rf /backup/*"
echo ""
echo "Only reset config:"
echo "  sudo rm /etc/rapiba/rapiba.conf"
echo "  sudo cp rapiba/etc/rapiba.conf /etc/rapiba/"
echo ""
